import type { IEvent } from "@/interfaces/eventInterface.ts";

export const mockEvents: IEvent[] = [
	{
		id: 'conf-2023',
		name: 'Научная конференция 2023',
		type: 'conference',
		date: '15.02.2024',
		time: '09:00 - 17:00',
		location: 'Москва, ул. Ленина, д. 1, ауд. 101',
		description: 'Ежегодная научная конференция, посвященная последним достижениям в различных областях науки.',
		sections: ['Научные исследования', 'Методические разработки'],
		registrationFields: {
			faculties: ['ФИТ', 'ФЭМ'],
			courses: ['1', '2', '3', '4'],
			teachers: ['Иванов И.И.', 'Петров П.П.'],
			presentationSections: ['Научные исследования', 'Методические разработки'],
		},
	},
	{
		id: 'seminar-ml',
		name: 'Семинар по машинному обучению',
		type: 'seminar',
		date: '28.02.2024',
		time: '10:00 - 13:00',
		location: 'Санкт-Петербург, ул. Невский, д. 10, ауд. 305',
		description: 'Обсуждение последних трендов в ML.',
		sections: ['Введение в ML', 'Глубокое обучение'],
		registrationFields: {
			faculties: ['ФКН', 'ПМИ'],
			courses: ['3', '4', 'Магистратура 1'],
			teachers: ['Сидоров С.С.'],
			presentationSections: ['Введение в ML', 'Глубокое обучение'],
			englishLevels: ['B1', 'B2', 'C1'],
			needsTranslator: true,
		},
	},
	{
		id: 'round-table-web-2024',
		name: 'Круглый стол: Будущее веб-разработки',
		type: 'roundTable',
		date: '10.03.2024',
		time: '14:00 - 16:00',
		location: 'Екатеринбург, ул. Малышева, 51, ауд. 501',
		description: 'Обсуждение новых фреймворков и подходов в frontend и backend.',
		sections: ['Frontend', 'Backend', 'DevOps'],
		registrationFields: {
			faculties: ['ФИТ', 'ИРИТ-РТФ'],
			courses: ['2', '3', '4'],
			teachers: ['Кузнецов К.К.', 'Смирнова С.С.'],
			presentationSections: ['Frontend', 'Backend'],
		},
	},
	{
		id: 'conf-data-science-2024',
		name: 'Конференция по Data Science',
		type: 'conference',
		date: '20.03.2024',
		time: '10:00 - 18:00',
		location: 'Новосибирск, Академгородок, ул. Пирогова, 2',
		description: 'Крупнейшая конференция по анализу данных и искусственному интеллекту в Сибири.',
		sections: ['Big Data', 'Computer Vision', 'Natural Language Processing'],
		registrationFields: {
			faculties: ['ММФ', 'ФИТ'],
			courses: ['3', '4', 'Магистратура 1', 'Магистратура 2'],
			teachers: ['Волков В.В.', 'Зайцева З.З.'],
			presentationSections: ['Big Data', 'Computer Vision', 'Natural Language Processing'],
			hasTranslatorEducation: true,
		},
	},
	{
		id: 'seminar-cybersec-2024',
		name: 'Семинар по кибербезопасности',
		type: 'seminar',
		date: '05.04.2024',
		time: '11:00 - 14:00',
		location: 'Казань, ул. Кремлевская, 35, ауд. 210',
		description: 'Практические аспекты защиты информации в современных системах.',
		sections: ['Сетевая безопасность', 'Криптография'],
		registrationFields: {
			faculties: ['ИВМиИТ', 'ИТИС'],
			courses: ['4', 'Магистратура 1'],
			teachers: ['Ахметов А.А.'],
			presentationSections: ['Сетевая безопасность'],
		},
	},
	{
		id: 'conf-eco-2024',
		name: 'Экологический форум 2024',
		type: 'conference',
		date: '18.04.2024',
		time: '09:30 - 16:30',
		location: 'Сочи, Олимпийский парк, Медиацентр',
		description: 'Обсуждение глобальных экологических проблем и путей их решения.',
		sections: ['Устойчивое развитие', 'Переработка отходов', 'Зеленая энергетика'],
		registrationFields: {
			faculties: ['Институт экологии', 'Биологический факультет'],
			courses: ['2', '3', '4'],
			teachers: ['Орлов О.О.', 'Лебедева Л.Л.'],
			presentationSections: ['Устойчивое развитие', 'Зеленая энергетика'],
			needsTranslator: true,
		},
	},
	{
		id: 'round-table-history-2024',
		name: 'Круглый стол: Переосмысление истории',
		type: 'roundTable',
		date: '25.04.2024',
		time: '15:00 - 17:00',
		location: 'Москва, ул. Мясницкая, 20, ауд. 420',
		description: 'Дискуссия о новых подходах к изучению исторических событий.',
		sections: ['Архивные исследования', 'Цифровая гуманитаристика'],
		registrationFields: {
			faculties: ['Исторический факультет', 'Философский факультет'],
			courses: ['1', '2', '3', '4', 'Магистратура 1', 'Магистратура 2'],
			teachers: ['Романов Р.Р.'],
			presentationSections: ['Архивные исследования'],
		},
	},
	{
		id: 'seminar-ux-ui-2024',
		name: 'Семинар по UX/UI дизайну',
		type: 'seminar',
		date: '15.05.2024',
		time: '12:00 - 15:00',
		location: 'Онлайн, Zoom',
		description: 'Создание интуитивно понятных и красивых интерфейсов.',
		sections: ['Исследование пользователей', 'Прототипирование', 'Дизайн-системы'],
		registrationFields: {
			faculties: ['Школа дизайна', 'ФКН'],
			courses: ['2', '3', '4'],
			teachers: ['Павлова П.П.'],
			presentationSections: ['Прототипирование', 'Дизайн-системы'],
			englishLevels: ['A2', 'B1', 'B2'],
		},
	},
	{
		id: 'conf-arch-2024',
		name: 'Конференция по современной архитектуре',
		type: 'conference',
		date: '20.05.2024',
		time: '10:00 - 18:00',
		location: 'Москва, Центральный Дом Архитектора',
		description: 'Тенденции и инновации в городской архитектуре и дизайне.',
		sections: ['Урбанистика', 'Зеленое строительство', 'BIM-технологии'],
		registrationFields: {
			faculties: ['МАРХИ', 'Институт строительства и архитектуры'],
			courses: ['3', '4', 'Магистратура 1'],
			teachers: ['Соколов С.А.', 'Белова Е.М.'],
			presentationSections: ['Урбанистика', 'Зеленое строительство'],
		},
	},
	{
		id: 'seminar-fintech-2024',
		name: 'Семинар: Финтех-революция',
		type: 'seminar',
		date: '25.05.2024',
		time: '11:00 - 13:00',
		location: 'Онлайн, Teams',
		description: 'Блокчейн, криптовалюты и будущее банковского сектора.',
		sections: ['Блокчейн', 'Цифровые валюты'],
		registrationFields: {
			faculties: ['ФЭМ', 'ФКН'],
			courses: ['4', 'Магистратура 1', 'Магистратура 2'],
			teachers: ['Морозов М.А.'],
			presentationSections: ['Блокчейн'],
			englishLevels: ['B2', 'C1'],
		},
	},
	{
		id: 'round-table-ai-ethics-2024',
		name: 'Круглый стол по этике ИИ',
		type: 'roundTable',
		date: '01.06.2024',
		time: '16:00 - 18:00',
		location: 'Сколково, Технопарк',
		description: 'Этические дилеммы и регулирование искусственного интеллекта.',
		sections: ['Этика в ИИ', 'Регулирование технологий'],
		registrationFields: {
			faculties: ['Философский факультет', 'Юридический факультет', 'ФКН'],
			courses: ['3', '4', 'Магистратура 1'],
			teachers: ['Новикова Н.В.', 'Козлов Д.С.'],
			presentationSections: ['Этика в ИИ'],
		},
	},
	{
		id: 'conf-biotech-2024',
		name: 'Биотехнологическая конференция',
		type: 'conference',
		date: '05.06.2024',
		time: '09:00 - 17:00',
		location: 'Пущино, ИБ РАН',
		description: 'Новейшие разработки в генной инженерии и медицине.',
		sections: ['Генная инженерия', 'Фармакология', 'Биоинформатика'],
		registrationFields: {
			faculties: ['Биологический факультет', 'Факультет биоинженерии'],
			courses: ['3', '4', 'Магистратура 1', 'Магистратура 2'],
			teachers: ['Денисов Д.А.', 'Павлова О.И.'],
			presentationSections: ['Генная инженерия', 'Биоинформатика'],
			hasTranslatorEducation: true,
		},
	},
	{
		id: 'seminar-marketing-2024',
		name: 'Семинар по цифровому маркетингу',
		type: 'seminar',
		date: '10.06.2024',
		time: '10:00 - 14:00',
		location: 'Санкт-Петербург, ул. Итальянская, 15',
		description: 'Стратегии продвижения в социальных сетях и поисковых системах.',
		sections: ['SMM', 'SEO', 'Контент-маркетинг'],
		registrationFields: {
			faculties: ['Высшая школа менеджмента', 'Факультет журналистики'],
			courses: ['2', '3', '4'],
			teachers: ['Федорова А.В.'],
			presentationSections: ['SMM', 'Контент-маркетинг'],
		},
	},
	{
		id: 'conf-robotics-2024',
		name: 'Конференция по робототехнике',
		type: 'conference',
		date: '15.06.2024',
		time: '09:30 - 18:00',
		location: 'Иннополис, Университет Иннополис',
		description: 'Промышленные и коллаборативные роботы, автономные системы.',
		sections: ['Промышленные роботы', 'Автономная навигация', 'Машинное зрение'],
		registrationFields: {
			faculties: ['ИТИС', 'ИРИТ-РТФ'],
			courses: ['3', '4', 'Магистратура 1'],
			teachers: ['Григорьев Г.П.', 'Степанова С.С.'],
			presentationSections: ['Автономная навигация', 'Машинное зрение'],
			needsTranslator: true,
		},
	},
	{
		id: 'round-table-space-2024',
		name: 'Круглый стол: Частный космос',
		type: 'roundTable',
		date: '20.06.2024',
		time: '15:00 - 17:00',
		location: 'Москва, Музей космонавтики',
		description: 'Перспективы и вызовы частной космонавтики в России и в мире.',
		sections: ['Ракетные технологии', 'Спутниковые системы'],
		registrationFields: {
			faculties: ['Аэрокосмический факультет', 'ФЭМ'],
			courses: ['4', 'Магистратура 1', 'Магистратура 2'],
			teachers: ['Борисов Б.А.'],
			presentationSections: ['Ракетные технологии'],
		},
	},
	{
		id: 'seminar-gamedev-2024',
		name: 'Семинар по разработке игр',
		type: 'seminar',
		date: '25.06.2024',
		time: '12:00 - 16:00',
		location: 'Онлайн, Discord',
		description: 'От идеи до релиза: полный цикл разработки инди-игры.',
		sections: ['Геймдизайн', 'Программирование на Unity', '3D-моделирование'],
		registrationFields: {
			faculties: ['Школа дизайна', 'ПМИ'],
			courses: ['1', '2', '3', '4'],
			teachers: ['Михайлов М.М.'],
			presentationSections: ['Геймдизайн', 'Программирование на Unity'],
			englishLevels: ['A2', 'B1', 'B2', 'C1'],
		},
	},
	{
		id: 'conf-physics-2024',
		name: 'Конференция по теоретической физике',
		type: 'conference',
		date: '01.07.2024',
		time: '10:00 - 17:00',
		location: 'Черноголовка, ИТФ им. Ландау',
		description: 'Обсуждение фундаментальных вопросов квантовой механики и теории струн.',
		sections: ['Квантовая теория поля', 'Теория струн', 'Космология'],
		registrationFields: {
			faculties: ['Физический факультет'],
			courses: ['4', 'Магистратура 1', 'Магистратура 2'],
			teachers: ['Егоров Е.П.', 'Васильева В.А.'],
			presentationSections: ['Квантовая теория поля', 'Космология'],
			hasTranslatorEducation: true,
		},
	},
	{
		id: 'seminar-vr-ar-2024',
		name: 'Семинар по VR/AR технологиям',
		type: 'seminar',
		date: '05.07.2024',
		time: '14:00 - 17:00',
		location: 'Москва, Artplay',
		description: 'Применение технологий виртуальной и дополненной реальности в бизнесе и искусстве.',
		sections: ['VR-тренажеры', 'AR-приложения', 'Интерактивное искусство'],
		registrationFields: {
			faculties: ['Школа дизайна', 'ФИТ'],
			courses: ['3', '4'],
			teachers: ['Алексеев А.А.'],
			presentationSections: ['AR-приложения', 'Интерактивное искусство'],
		},
	},
];
